---
- name: HOOK update postgres config for installcheck
  blockinfile:
    path: /opt/postgres/data/conf.d/9999-override.conf
    create: yes
    owner: postgres
    group: postgres
    block: |
      bdr.node1_superuser_dsn = 'host=node1 dbname=bdrdb user=postgres'
      bdr.node2_superuser_dsn = 'host=node2 dbname=bdrdb user=postgres'
    state: present
