---
- name: Update postgres config for installcheck and query logging
  blockinfile:
    path: /opt/postgres/data/conf.d/9999-override.conf
    create: yes
    owner: postgres
    group: postgres
    block: |
      bdr.node1_superuser_dsn = 'host=node1 dbname=bdrdb user=postgres'
      bdr.node2_superuser_dsn = 'host=node2 dbname=bdrdb user=postgres'
      log_statement = 'all'

- name: Update postgres directory ownership
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    recurse: yes
  loop:
    - /opt/postgres
    - /var/log/postgres
    - /var/run/postgresql

- name: Update rsyslog config to enable postgres logging
  blockinfile:
    path: /etc/rsyslog.d/99-override.conf
    create: yes
    block: |
      $PrivDropToUser postgres
      $PrivDropToGroup postgres

- name: Restart rsyslog service
  service:
    name: rsyslog
    state: restarted

- name: Ensure all packages are up to date
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
