#!/bin/bash

# eval `ssh-agent`
# ssh-add ~/.ssh/id_ed25519

NO_DEPROVISION=1
AV_TAG_CLEANUP=0

docker rm -f prod01-db-ps03
docker rm -f prod01-db-ps04
docker rm -f prod01-db-ps01

tpaexec provision .
tpaexec deploy .
