---
architecture: BDR-Simple
cluster_name: fromsource
cluster_tags: {}

forward_ssh_agent: 'yes'

cluster_vars:
  postmaster_oom_score_adj: 0
  postgres_oom_score_adj: 500

  bdr_database: bdrdb
  bdr_node_group: bdrgroup
  enable_harp: false

  postgres_version: '13'
  postgresql_flavour: postgresql
  extra_postgres_extensions:
    - pglogical
  postgres_coredump_filter: '0xff'
  postgres_home: "/opt/postgres/src"
  extra_bashrc_lines:
    - export SRC="/opt/postgres/src"
    - echo "" && echo "SOURCE DIRECTORY - ${SRC}" && echo ""
  postgres_users:
  - username: some_superuser
    generate_password: false
    role_attrs:
    - superuser
  - username: some_nonsuperuser
    generate_password: false

  tpa_2q_repositories:
    - products/pglogical3_7/release
    - products/bdr3_7/release
  preferred_python_version: python3
  use_volatile_subscriptions: false

  # The tpaexec "src" method doesn't seem to work at this time.
  # We'll pull in the postgres source in hooks/post-deploy.yml instead.
  install_from_source:
  - name: pglogical3
    git_repository_url: git@github.com:EnterpriseDB/pglogical.git
    git_repository_ref: REL3_7_STABLE
    source_directory: /opt/postgres/src/pglogical
    build_directory: /opt/postgres/src/pglogical
  - name: bdr3
    git_repository_url: git@github.com:EnterpriseDB/bdr.git
    git_repository_ref: REL3_7_STABLE
    source_directory: /opt/postgres/src/bdr
    build_directory: /opt/postgres/src/bdr

  packages:
    Ubuntu:
      - bison
      - flex
      - gettext
      - iputils-ping
      - libedit-dev
      - libfile-which-perl
      - libgettextpo-dev
      - libipc-run-perl
      - libjson-perl
      - libkrb5-dev
      - libldap-dev
      - liblocale-msgfmt-perl
      - libpam-dev
      - libperl-dev
      - libpq-dev
      - libreadline-dev
      - libselinux-dev
      - libssl-dev
      - libsystemd-dev
      - libtest-simple-perl
      - libxml2-dev
      - libxml2-utils
      - libxml-generator-perl
      - libxslt-dev
      - net-tools
      - perl
      - pkg-config
      - python3-dev
      - python3-psycopg2
      - systemtap-sdt-dev
      - tclsh
      - tcl-dev
      - uuid-dev
      - vim
      - xsltproc
      - zlib1g-dev
      - software-properties-common

locations:
- Name: first

instance_defaults:
  image: tpa/ubuntu:20.04
  platform: docker
  location: 0
  role:
  - primary
  - bdr
  vars:
    ansible_user: root

instances:
- Name: node1
  node: 1
- Name: node2
  node: 2
