---
architecture: BDR-Simple
cluster_name: fromsource
cluster_tags: {}

forward_ssh_agent: 'yes'

cluster_vars:
  postmaster_oom_score_adj: 0
  postgres_oom_score_adj: 500
  bdr_database: bdrdb
  bdr_node_group: bdrgroup
  enable_harp: false
  postgres_version: '13'
  postgresql_flavour: postgresql
  extra_postgres_extensions:
    - pglogical
  postgres_coredump_filter: '0xff'
  tpa_2q_repositories:
    - products/pglogical3_7/release
    - products/bdr3_7/release
  preferred_python_version: python3
  use_volatile_subscriptions: true
  install_from_source:
  - name: pglogical3
    git_repository_url: git@github.com:EnterpriseDB/pglogical.git
    git_repository_ref: REL3_7_8
    source_directory: /opt/postgres/src/pglogical
    build_directory: /opt/postgres/src/pglogical
  - name: bdr3
    git_repository_url: git@github.com:EnterpriseDB/bdr.git
    git_repository_ref: REL3_7_8
    source_directory: /opt/postgres/src/bdr
    build_directory: /opt/postgres/src/bdr
  packages:
    RedHat:
      - perl-XML-Generator
      - perl-IPC-Run
      - perl-File-Which
      - perl-JSON
      - perl-Test-Simple
    Ubuntu:
      - bison
      - flex
      - gettext
      - iputils-ping
      - libedit-dev
      - libfile-which-perl
      - libgettextpo-dev
      - libipc-run-perl
      - libjson-perl
      - libkrb5-dev
      - libldap-dev
      - liblocale-msgfmt-perl
      - libpam-dev
      - libperl-dev
      - libpq-dev
      - libreadline-dev
      - libselinux-dev
      - libssl-dev
      - libsystemd-dev
      - libtest-simple-perl
      - libxml2-dev
      - libxml2-utils
      - libxml-generator-perl
      - libxslt-dev
      - net-tools
      - perl
      - pkg-config
      - python3-dev
      - python3-psycopg2
      - systemtap-sdt-dev
      - tclsh
      - tcl-dev
      - uuid-dev
      - vim
      - xsltproc
      - zlib1g-dev
      - software-properties-common
  # postgres_installation_method: src
  # postgres_git_url: git://git.postgresql.org/git/postgresql.git
  # postgres_git_ref: REL_13_3
  # postgres_extra_configure_env:
  #   CFLAGS: "-O0"
  # postgres_configure_opts:
  #   - --enable-tap-tests
  #   - --enable-debug
  #   - --with-openssl
  #   - --config-cache
  # postgres_make_command: "make -j4 -s"
  # postgres_build_targets:
  #   - "all"
  #   - "-C contrib"
  #   - "-C src/test/regress"
  #   - "-C src/test/perl"          
  #   - "-C src/test/isolation"
  # postgres_install_targets:
  #   - "install"
  #   - "-C contrib install"
  #   - "-C src/test/regress install-tests"
  #   - "-C src/test/perl install"
  #   - "-C src/test/isolation install"
  # unix_socket_directories:
  #   - /var/run/postgresql
  #   - /tmp


locations:
- Name: first

instance_defaults:
  image: tpa/ubuntu:20.04
  platform: docker
  # memory: 4G
  # memory_reservation: 2G
  # shm_size: 256M
  location: 0
  role:
  - primary
  - bdr
  vars:
    ansible_user: root

instances:
- Name: node1
  node: 1
- Name: node2
  node: 2
