#!/bin/bash

# Pass any command line parameter to prevent a full rebuild (only for subsequent runs)
NO_RESET=$1

# Use the current user's GIT SSH key (must exist!)
eval `ssh-agent`
ssh-add ~/.ssh/id_ed25519

# Ensure tpaexec does not destroy the cluster
export NO_DEPROVISION=1

if [ -z "$NO_RESET" ]; then
    # Start over
    echo "START OVER"
    docker rm -f node1
    docker rm -f node2

    tpaexec provision .
    if [ $? -ne 0 ]; then
        exit
    fi

    tpaexec deploy .
else
    # Just rebuild existing source
    echo "REBUILD EXISTING SOURCE"

    tpaexec deploy . --tags post-deploy
fi

exit
